/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Expressions/Concerned.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Expressions/Concerned.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
  }
  materials: {
    ['color chart']: THREE.MeshStandardMaterial
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Concerned = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Expressions/Concerned.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
        <mesh geometry={nodes.Cube006.geometry}>
          <Outlines />
          <meshBasicMaterial map={materials['color chart'].map} />
        </mesh>
        <mesh geometry={nodes.Cube006_1.geometry}>
          <Outlines />
          <meshBasicMaterial map={materials['murph color'].map} />
        </mesh>
    </group>
  )
})
export default Concerned

useGLTF.preload('/3DModels/Expressions/Concerned.glb')
