/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Bug.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Bug.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
  }
  materials: {
    ['color chart']: THREE.MeshStandardMaterial
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Bug = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Bug.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
        <mesh geometry={nodes.Cube014.geometry} rotation={[0, Math.PI, 0]}>
          <Outlines />
          <meshBasicMaterial map={materials['color chart'].map} />
        </mesh>
        {/*<mesh geometry={nodes.Cube014_1.geometry}>
          <Outlines />
          <meshBasicMaterial map={materials['murph color'].map} />
        </mesh>*/}
      <group position={[0, 2.5, 1]} rotation={[0, Math.PI, 0]} scale={0.5}>
          {props.children}
      </group>
    </group>
  )
})
export default Bug

useGLTF.preload('/3DModels/Bug.glb')
