/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Butter.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Butter.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    butter: THREE.Mesh
  }
  materials: {
    ['color chart']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Butter = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Butter.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.butter.geometry} position={[-2.5, 0, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials['color chart'].map} />
      </mesh>
      <group position={[0.5, 0.75, 0.75]} rotation={[-Math.PI * 0.125, Math.PI * 0.95, Math.PI * 0.0625]} scale={0.5}>
          {props.children}
      </group>
    </group>
  )
})
export default Butter

useGLTF.preload('/3DModels/Butter.glb')
