/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Coffin.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Coffin.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    coffin: THREE.Mesh
  }
  materials: {
    ['color chart']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Coffin = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Coffin.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.coffin.geometry} rotation={[0, Math.PI, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials['color chart'].map} />
      </mesh>
      <group position={[0, 12, 1.5]} rotation={[0, Math.PI, 0]}>
          {props.children}
      </group>
    </group>
  )
})
export default Coffin

useGLTF.preload('/3DModels/Coffin.glb')
