/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Dog.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Dog.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CAin: THREE.Mesh
  }
  materials: {
    cain: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Dog = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Dog.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.CAin.geometry} position={[0, -1, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials.cain.map} />
      </mesh>
      <group position={[0, 1.25, 1.25]} rotation={[0, Math.PI, 0]} scale={0.5}>
          {props.children}
      </group>
    </group>
  )
})
export default Dog

useGLTF.preload('/3DModels/Dog.glb')
