/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Eyes.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Eyes.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Eyes: THREE.Mesh
  }
  materials: {
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Eyes = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Eyes.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Eyes.geometry}>
        <Outlines />
        <meshBasicMaterial map={materials['murph color'].map} />
      </mesh>
        <group position={[0, 0, 1.5]} rotation={[0, Math.PI, 0]}>
            {props.children}
        </group>
    </group>
  )
})
export default Eyes

useGLTF.preload('/3DModels/Eyes.glb')
