/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Mug.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Mug.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MUG: THREE.Mesh
  }
  materials: {
    ['color chart']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Mug = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Mug.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.MUG.geometry} position={[-0.25, 0, 0]} rotation={[0, -Math.PI * 0.5, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials['color chart'].map} />
      </mesh>
      <group position={[0, 1, 1]} rotation={[0, Math.PI, 0]} scale={0.5}>
          {props.children}
      </group>
    </group>
  )
})
export default Mug

useGLTF.preload('/3DModels/Mug.glb')
