/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Murph.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Murph.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MURPH: THREE.Mesh
  }
  materials: {
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Murph = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Murph.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.MURPH.geometry} rotation={[0, Math.PI, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials['murph color'].map} />
      </mesh>
    </group>
  )
})
export default Murph

useGLTF.preload('/3DModels/Murph.glb')
