/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Snake.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Snake.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    snake: THREE.Mesh
  }
  materials: {
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Snake = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Snake.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.snake.geometry} rotation={[0, -Math.PI * 0.5, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials['murph color'].map} />
      </mesh>
      <group position={[-0.375, 3, 1]} rotation={[0, Math.PI, 0]} scale={0.5}>
          {props.children}
      </group>
    </group>
  )
})
export default Snake

useGLTF.preload('/3DModels/Snake.glb')
