/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Spring.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Spring.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    spring: THREE.Mesh
  }
  materials: {
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Spring = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Spring.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.spring.geometry}>
        <Outlines />
        <meshBasicMaterial map={materials['murph color'].map} />
      </mesh>
      <group position={[0, 4, 2]} rotation={[0, Math.PI, 0]}>
          {props.children}
      </group>
    </group>
  )
})
export default Spring

useGLTF.preload('/3DModels/Spring.glb')
