/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../WebStormProjects/ggj-2024/public/3DModels/Worm.glb -F -t -O -b -o ../../WebStormProjects/ggj-2024/src/components/3D/Worm.tsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    NurbsPath001: THREE.Mesh
    NurbsPath001_1: THREE.Mesh
  }
  materials: {
    ['color chart']: THREE.MeshStandardMaterial
    ['murph color']: THREE.MeshStandardMaterial
  }
}

type Props = JSX.IntrinsicElements['group']

const Worm = forwardRef<THREE.Group, Props>((props: Props, ref) => {
  const { nodes, materials } = useGLTF('/3DModels/Worm.glb') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.NurbsPath001.geometry} rotation={[0, Math.PI * 0.5, 0]}>
        <Outlines />
        <meshBasicMaterial map={materials['color chart'].map} />
      </mesh>
      <group position={[0, 1, 2.75]} rotation={[0, Math.PI, 0]} scale={0.25}>
          {props.children}
      </group>
    </group>
  )
})
export default Worm

useGLTF.preload('/3DModels/Worm.glb')
